let titles = [
  `Private Pool House with Amazing Views!`,
  `Pirates of the Caribbean Getaway`,
  `The Crow's Nest: Urban Cabin`,
  `Private Modern Guesthouse near Beverly Hills`,
  `SilverLake studio with view/parking`,
  `Stylish Hollywood Loft with Views!`,
  `BEST Downtown Loft on Airbnb!`,
  `Great location on a budget, POOL`,
  `Rustic Space Perched in the Hollywood Hills`,
  `Private Guest Suite in Top Location`,
  `Admire Amazing Views from a Modern, Zen-like Guest Suite`,
  `PRIVATE CENTRAL GUESTHOUSE - LOVELY`,
  `Los Angeles HUGE & Beautiful Loft (ST V. 504)`,
  `MY LITTLE PARIS IN LOS ANGELES With free parking.`,
  `Luxury Seaside Studio, Pool`,
  `Picture Perfect California Bungalow`,
  `Cozy Studio Guest House with Courtyard Garden`,
  `Los Feliz Oasis Cottage, Pool and Spa`,
  `Treetop Terrace`,
  `Tranquil and Elegant Apartment Close to the Beaches`,
  `Licensed luxurious guesthouse with Parking Garage`,
  `Beautiful Hollywood Getaway (2 blocks from Metro!)`,
  `Echo Park Retreat with Views`,
  `The Little Bungalow`,
  `Charming Craftsman with Outdoor Shower`,
  `Gorgeous Mid-Century Modern Loft with Fire Pit`,
  `Relax Poolside in Delightful Private Guest Suite!`,
  `Charming New Craftsman Studio`,
  `Enchanting Artist's Guest House`,
  `Cozy Guest House w/ Stunning Views`,
  `Writer's Retreat away from traffic`,
  `Modern Studio URBAN FOOD FOREST private parking`,
  `Explore the City from a Sunny Palms Apartment`,
  `HEART of LA (Private) TIKI HOUSE W/Breakfast`,
  `Stand Alone Studio Cottage Retreat`,
  `Luxury By the Lights Of Universal!`,
  `Topanga Tree House Retreat`,
  `Adorable Arts District Guest House`,
  `SUPER COZY AND STYLISH 1 BDR APT IN LOS ANGELES`,
  `Private Guest House Overlooking the Pool.`,
  `Modern Work/Live Hillside Studio`,
  `A Beautiful and Private Guesthouse`,
  `Studio Apartment/Private Entrance/Private Parking`,
  `Charming Mid City Private Studio`,
  `The Great Hollywood Hills Private Guest House`,
  `Modern Fully Renovated 3 bed 1808`,
  `Stylish Hollywood Apt Sleeps 5`,
  `Modern Design Guesthouse with Private Backyard Skate Ramp`,
  `SPINNAKER GUEST HOUSE-FREE BIKES`,
  `Luxury Pool House Newly Built Prime West LA Villa`,
  `The Outlaw Hideaway fort.`,
  `New Listing Private GuestHouse with Kitchen&Bath`,
  `Lovely private guesthouse`,
  `LUXURY Guesthouse + Cabana & Pool !`,
  `Private unit with kitchen and good location`,
  `Downtown Los Angeles Studio`,
  `Studio: Private Entry & Hot Tub`,
  `Bright, White, Clean 1BA+BR/Parking`,
  `Visitors Dream Pad/Historical 1920s`,
  `L.A. Lifestyle--like you live here`,
  `Downtown Los Angeles Penthouse`,
  `Beautiful Cozy Spanish home - private room/bath.`,
  `The James Bond Room in Atomic Loft`,
  `L.A. Hillside retreat`,
  `Comuna Factory King Bedroom!!`,
  `New Private Bedroom & Beautiful Large Bath #3`,
  `Private Room and Bath in Cozy House`,
  `Room in Fantastic Location, Popular Place for Getaways`,
  `Large Suite Private Bedr & Bath by Sunset Bl`,
  `Comuna Factory Tiny Cedar Pagoda Room:)`,
  `Gr8 Location, 3 Beds w/ Private Bath!`,
  `Silver Lake Pied-a-Terre / Private Guest Suite`,
  `Relaxed Poolside Living at a Cozy Canoga `,
  `Private Guest Room & Patio Santa Monica`,
  `Beautiful private room and bath. Private entrance.`,
  `Hollywood Hotel Owners Suite 237`,
  `Oak Leaf Room FreeParking`,
  `Super Hosts have a Comfy Room!! Walk To Universal!`,
  `Green : Beverly Private Bedroom`,
  `Unwind at a Tranquil, Quiet Home`,
  `The@Hollywood, Purple`,
  `private Space/Treehouse in a mid century home.`,
  `Lovely Home, Super MidCity Location`,
  `Welcome! Private Room & Private Bath`,
  `Desirable, Clean Room in Central LA Location!`,
  `SPACIOUS BEDROOM IN PRIVATE SUITE`, 
  `GEM IN THE CITY #Q`,
  `Comuna Factory Celestial Room!!`,
  `B&B Walk to Beach - Breezy Homebase`,
  `Private Suite (including Bath) in Echo Park Home`,
  `private house`,
  `Bloom Room @ Limelight Manor`,
  `Modern Shabby Chic Sanctuary Studio`,
  `Los Angeles House with Huge Yard`,
  `Master Bedroom with private bathroom & balcony`,
  `Beautiful room-special place-Walk 2 everything`,
  `Great Views Easy Access to Downtown`,
  `Zen Retreat with Gorgeous Views`,
  `Cocoon room with private bathroom!`,
  `Tranquil Suite in a Bungalow`,
  `Paradise studio, Hollywood gated, own entrance.`
]

module.exports.titles = titles;